'use strict';

/**
 * Journey: J-session-streamed
 * Category: Dispatch & Execution
 *
 * What this tests:
 *   On 2026-09-14 slices 358 and 363 were killed at 28 and 24 minutes by
 *   ERR_CHILD_PROCESS_STDIO_MAXBUFFER. execFile holds a session's WHOLE output in
 *   memory so it can hand it to a callback, and a dashboard slice that reads
 *   screenshots logs 160-420 KB per image. 688 lines of work were left uncommitted
 *   and the rom-358/363 logs are gone. Commit a8da61f raised Sam's cap to 256 MB,
 *   which moved the cliff and bought the move by letting one session hold a quarter
 *   of a gigabyte of strings; Jordan's cap stayed at 10 MB.
 *
 *   This file holds the removal: the session is read line by line as it arrives,
 *   nothing holds the output, and every number, log and error file the run used to
 *   take from the whole text is still taken — from the one line that carries it,
 *   four whole-session flags, and the last 64 KB of each stream.
 *
 *   The oracle for "still taken" is the session's own log. It IS the whole stdout,
 *   byte for byte, so the functions that used to be handed the whole stdout —
 *   sessionTelemetry, attributeRun, extractSessionId — are run over the log here
 *   and compared with what the run recorded. A drift shows up as a mismatch.
 *
 * Guards:
 *   slice-396-ac-1 — a 300 MB Sam session finishes and is recorded
 *   slice-396-ac-2 — a 300 MB Jordan session finishes and is recorded
 *   slice-396-ac-3 — 300 MB streams past without 64 MB of orchestrator memory
 *   slice-396-ac-4 — every recorded value equals what the whole stdout gives
 *   slice-396-ac-5 — the ERROR file reads as today, with bounded stdout/stderr
 *   slice-396-ac-6 — the rate-limit pause reads the whole session, the reset the tail
 *   slice-396-ac-7 — the API retry reads the whole session
 *   slice-396-ac-8 — the log is written while the session runs, never rewritten
 *   slice-396-ac-9 — Jordan's review numbers equal what his whole stdout gives
 *   traps 1-5     — split chunks, stdin, ENOENT, pause/resume/abort, stderr-only
 *
 * Fixture isolation (#99992): every byte of state lives under fs.mkdtempSync(os.tmpdir())
 * with a LOCAL BARE origin and its own copy of bridge/ and lib/, whose bridge.config.json
 * points claudeCommand at a fixture script. LOGS_DIR, the errors directory and the queue
 * all resolve inside that copy, so no live log, register or queue file is touched. The
 * 300 MB fixtures are generated by the fixture child at run time and go with the temp
 * directory — never under bridge/logs/, which is the disk that filled up on 09-14.
 * Worktrees are the one shared path (WORKTREE_BASE is hardcoded): the ids here are in
 * the 9631xx band, which no real slice uses, and every one is swept in after().
 */

// @ac-hash: slice-396-ac-1 sha256:7130134a4c9f43e3668b12b2ee00aa1fc9b7ea7e8b2df1db06c1443ca662eddd
// @ac-hash: slice-396-ac-2 sha256:e09741a8d93434282eb9d2af2beeaa48a27804dfaf5506723454bdeedb8de1c7
// @ac-hash: slice-396-ac-3 sha256:630ca488eb03a20da6dc88e0255ec6c49598beeeae06d948c6cd28231474157b
// @ac-hash: slice-396-ac-4 sha256:f9600abf9dd72b0f8828fa9608dee730e7d9d7687089535429c2f763aa241266
// @ac-hash: slice-396-ac-5 sha256:c6f5fe2e180f9a560242644956c4e6575061bcec117256bfc412513aba5f29a3
// @ac-hash: slice-396-ac-6 sha256:71fbe87a47e811cf05824d07851ed4c22845032a5d5b6572fa3d19e9e9f32d27
// @ac-hash: slice-396-ac-7 sha256:dca249b59494e18d0d90cac06e152daa5db0055a0a02edeec2885aedabc90104
// @ac-hash: slice-396-ac-8 sha256:4c0c1d580fec1a50a470ff8549ead2732e360726a651121611f499bf87b3c981
// @ac-hash: slice-396-ac-9 sha256:80ecfda5d1d956e45f90f3191411f64aee75e38c5f597b731f50e1ccb1a1dfcf

const { test, after } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const crypto = require('node:crypto');
const { execFileSync, spawnSync, spawn } = require('node:child_process');

const REPO_ROOT = path.resolve(__dirname, '..', '..');
const ORCH_SRC = fs.readFileSync(path.join(REPO_ROOT, 'bridge', 'orchestrator.js'), 'utf8');

// The live modules, used only as ORACLES: what the whole text gives today.
const liveOrch = require('../../bridge/orchestrator');
const { attributeRun } = require('../../lib/build-timing');
const { streamSession } = require('../../lib/session-stream');

const TAIL = 65536;
const WORKTREE_BASE = '/tmp/ds9-worktrees';
const ID_BAND = '9631';

const GIT_ENV = {
  GIT_AUTHOR_NAME: 'Rom Fixture', GIT_AUTHOR_EMAIL: 'rom@fixture.test',
  GIT_COMMITTER_NAME: 'Rom Fixture', GIT_COMMITTER_EMAIL: 'rom@fixture.test',
  GIT_CONFIG_GLOBAL: '/dev/null', GIT_CONFIG_SYSTEM: '/dev/null',
};
const git = (args, cwd) => execFileSync('git', args,
  { cwd, encoding: 'utf8', env: { ...process.env, ...GIT_ENV }, stdio: ['ignore', 'pipe', 'pipe'] }).trim();

const tmpDirs = [];
const usedIds = [];
let idSeq = 0;
const nextId = () => { idSeq += 1; const id = `${ID_BAND}${String(idSeq).padStart(2, '0')}`; usedIds.push(id); return id; };

function dropFixture(fx) {
  try { fs.rmSync(fx.tmp, { recursive: true, force: true }); } catch (_) {}
  try { fs.rmSync(path.join(WORKTREE_BASE, String(fx.id)), { recursive: true, force: true }); } catch (_) {}
}

after(() => {
  for (const d of tmpDirs) { try { fs.rmSync(d, { recursive: true, force: true }); } catch (_) {} }
  for (const id of usedIds) {
    try { fs.rmSync(path.join(WORKTREE_BASE, String(id)), { recursive: true, force: true }); } catch (_) {}
  }
});

// ── the fixture claude ──────────────────────────────────────────────────────
// A step machine: the knobs file says what to write, when to pause, what to
// commit and what to exit with. It hashes everything it puts on stdout, so a
// 300 MB session can be compared with its log without either being read twice.

const FAKE_CLAUDE = `'use strict';
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const { execFileSync } = require('child_process');

const knobs = JSON.parse(fs.readFileSync(process.argv[2], 'utf8'));
const hash = crypto.createHash('sha256');
let bytesOut = 0;

const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

function push(stream, buf) {
  // Resolved by the write callback, not by the return value: a true return only
  // means "buffered", and exiting on a buffered pipe loses the tail.
  return new Promise((resolve) => stream.write(buf, () => resolve()));
}
function out(buf) {
  hash.update(buf);
  bytesOut += buf.length;
  return push(process.stdout, buf);
}
function err(buf) { return push(process.stderr, buf); }

function readStdin() {
  return new Promise((resolve) => {
    const parts = [];
    process.stdin.on('data', (c) => parts.push(c));
    process.stdin.on('end', () => resolve(Buffer.concat(parts)));
    process.stdin.on('error', () => resolve(Buffer.concat(parts)));
  });
}

function gitIn(cwd, args) {
  return execFileSync('git', args, { cwd, encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'] });
}

async function run() {
  for (const step of knobs.steps) {
    switch (step.op) {
      case 'stdin': {
        const buf = await readStdin();
        fs.writeFileSync(step.file, buf);
        break;
      }
      case 'pid':
        fs.writeFileSync(step.file, String(process.pid));
        break;
      case 'line':
        await out(Buffer.from(JSON.stringify(step.obj) + '\\n'));
        break;
      case 'raw':
        await out(Buffer.from(step.text, 'utf8'));
        break;
      case 'rawBytes':
        await out(Buffer.from(step.bytes));
        break;
      case 'bulk': {
        // stream-json the size of a real long build, made of ordinary assistant
        // turns so the attribution has something to walk.
        const pad = 'x'.repeat(step.lineBytes || 32768);
        let written = 0;
        while (written < step.bytes) {
          const line = Buffer.from(JSON.stringify({
            type: 'assistant',
            session_id: step.sessionId || 'bulk',
            message: { content: [{ type: 'text', text: pad }] },
          }) + '\\n');
          await out(line);
          written += line.length;
        }
        break;
      }
      case 'stderr':
        await err(Buffer.from(step.text, 'utf8'));
        break;
      case 'sleep':
        await sleep(step.ms);
        break;
      case 'repeat': {
        for (let i = 0; i < step.count; i++) {
          await sleep(step.ms);
          const text = String(step.text).replace('{i}', String(i));
          if (step.stream === 'stderr') await err(Buffer.from(text, 'utf8'));
          else await out(Buffer.from(text, 'utf8'));
        }
        break;
      }
      case 'forever': {
        // Talks until something kills it — the pause/resume/abort probe.
        for (let i = 0; ; i++) {
          await sleep(step.ms);
          await out(Buffer.from('{"type":"assistant","tick":' + i + '}\\n'));
        }
      }
      case 'done': {
        const dir = path.join(process.cwd(), 'bridge', 'queue');
        fs.mkdirSync(dir, { recursive: true });
        fs.writeFileSync(path.join(dir, step.id + '-DONE.md'), step.content);
        break;
      }
      case 'commit': {
        const cwd = process.cwd();
        fs.writeFileSync(path.join(cwd, step.file), step.content);
        gitIn(cwd, ['add', step.file]);
        gitIn(cwd, ['commit', '--quiet', '-m', step.message]);
        break;
      }
      case 'verdict': {
        const dir = path.join(process.cwd(), 'bridge', 'queue');
        fs.mkdirSync(dir, { recursive: true });
        fs.writeFileSync(path.join(dir, step.id + '-NOG.md'), step.content);
        break;
      }
      case 'dirty':
        fs.writeFileSync(path.join(process.cwd(), step.file), step.content);
        break;
      case 'pattern': {
        // Exactly step.count copies of a fixed unit, so the test knows the
        // session's bytes without reading them back.
        const unit = Buffer.from(step.unit, 'utf8');
        const per = step.chunkUnits || 64;
        let left = step.count;
        while (left > 0) {
          const n = Math.min(per, left);
          const parts = [];
          for (let i = 0; i < n; i++) parts.push(unit);
          const buf = Buffer.concat(parts);
          if (step.stream === 'stderr') await err(buf); else await out(buf);
          left -= n;
        }
        break;
      }
      case 'stamp':
        fs.writeFileSync(step.file, String(Date.now()));
        break;
      case 'hash':
        fs.writeFileSync(step.file, JSON.stringify({ sha256: hash.copy().digest('hex'), bytes: bytesOut }));
        break;
      default:
        throw new Error('unknown step ' + step.op);
    }
  }
}

run().then(() => {
  // exitCode, never process.exit: the pipes drain on the way out, so the last
  // bytes of a 300 MB session are in the log the test compares against.
  process.exitCode = knobs.exitCode || 0;
}, (e) => {
  process.stderr.write('fixture claude failed: ' + e.stack + '\\n');
  process.exitCode = 90;
});
`;

// ── the driver ──────────────────────────────────────────────────────────────
// One orchestrator process per run, pointed at the fixture copy. It exits on its
// own when invokeRom/invokeNog is done: both clear every timer they own, so the
// event loop drains and the process ends — which is how the test waits.

const DRIVER = `'use strict';
const fs = require('fs');
const path = require('path');

const job = JSON.parse(fs.readFileSync(process.argv[2], 'utf8'));
const WORK = job.work;
const QUEUE = path.join(WORK, 'bridge', 'queue');
const HEARTBEAT = path.join(WORK, 'bridge', 'heartbeat.json');

const gf = require(path.join(WORK, 'bridge', 'git-finalizer.js'));
const orch = require(path.join(WORK, 'bridge', 'orchestrator.js'));

orch._testSetProjectDir(WORK);
orch._testSetDirs(QUEUE, path.join(WORK, 'bridge', 'staged'), path.join(WORK, 'bridge', 'trash'));
orch._testSetRegisterFile(path.join(WORK, 'bridge', 'register.jsonl'));
orch._testSetHeartbeatFile(HEARTBEAT);
gf.init({
  PROJECT_DIR: WORK,
  registerEvent: () => {},
  log: () => {},
  HEARTBEAT_FILE: HEARTBEAT,
  QUEUE_DIR: QUEUE,
});

// The orchestrator's own footprint while the session streams.
const used = () => { const m = process.memoryUsage(); return m.heapUsed + m.arrayBuffers; };
const baseline = used();
let peak = 0;
const sampler = setInterval(() => { const d = used() - baseline; if (d > peak) peak = d; }, 250);
sampler.unref();
process.on('exit', () => {
  try { fs.writeFileSync(job.memFile, JSON.stringify({ baseline, peakDeltaBytes: peak })); } catch (_) {}
});

if (job.role === 'nog') {
  orch.invokeNog(job.id);
} else {
  const sliceContent = fs.readFileSync(job.inProgressPath, 'utf8');
  orch.invokeRom(
    sliceContent, job.donePath, job.inProgressPath, job.errorPath,
    job.id, job.inactivityMs, job.title, job.goal,
  );
}
`;

// ── fixture construction ────────────────────────────────────────────────────

function copyTree(from, to, filter) {
  fs.mkdirSync(to, { recursive: true });
  for (const entry of fs.readdirSync(from, { withFileTypes: true })) {
    if (entry.isDirectory()) continue;
    if (filter && !filter(entry.name)) continue;
    fs.copyFileSync(path.join(from, entry.name), path.join(to, entry.name));
  }
}

function buildFixture(id) {
  const tmp = fs.mkdtempSync(path.join(os.tmpdir(), `j-session-streamed-${id}-`));
  tmpDirs.push(tmp);
  const bare = path.join(tmp, 'origin.git');
  const work = path.join(tmp, 'work');

  git(['init', '--quiet', '--bare', '--initial-branch=main', bare], tmp);
  git(['clone', '--quiet', bare, work], tmp);
  git(['config', 'user.email', 'rom@fixture.test'], work);
  git(['config', 'user.name', 'Rom Fixture'], work);

  fs.writeFileSync(path.join(work, 'product.txt'), 'seed\n');
  git(['add', 'product.txt'], work);
  git(['commit', '--quiet', '-m', 'seed'], work);
  git(['push', '--quiet', 'origin', 'main'], work);
  git(['checkout', '--quiet', '-b', 'dev'], work);
  git(['push', '--quiet', '-u', 'origin', 'dev'], work);

  const bridgeDir = path.join(work, 'bridge');
  copyTree(path.join(REPO_ROOT, 'bridge'), bridgeDir, (f) => f.endsWith('.js'));
  copyTree(path.join(REPO_ROOT, 'bridge', 'state'), path.join(bridgeDir, 'state'), (f) => f.endsWith('.js'));
  copyTree(path.join(REPO_ROOT, 'lib'), path.join(work, 'lib'), (f) => f.endsWith('.js'));
  for (const d of ['queue', 'staged', 'trash', 'logs', 'errors', 'escalations', 'control']) {
    fs.mkdirSync(path.join(bridgeDir, d), { recursive: true });
  }

  const fakeClaude = path.join(tmp, 'fake-claude.js');
  fs.writeFileSync(fakeClaude, FAKE_CLAUDE);
  const driver = path.join(tmp, 'driver.js');
  fs.writeFileSync(driver, DRIVER);

  return {
    id, tmp, bare, work, driver, fakeClaude,
    bridgeDir,
    queue: path.join(bridgeDir, 'queue'),
    logs: path.join(bridgeDir, 'logs'),
    errors: path.join(bridgeDir, 'errors'),
    trash: path.join(bridgeDir, 'trash'),
    staged: path.join(bridgeDir, 'staged'),
    register: path.join(bridgeDir, 'register.jsonl'),
    knobs: path.join(tmp, 'knobs.json'),
    job: path.join(tmp, 'job.json'),
    mem: path.join(tmp, 'mem.json'),
  };
}

/** Points the fixture's config at the fixture claude (or at a command that is not there). */
function writeConfig(fx, { command, args } = {}) {
  fs.writeFileSync(path.join(fx.bridgeDir, 'bridge.config.json'), JSON.stringify({
    pollIntervalMs: 5000,
    inactivityTimeoutMs: 300000,
    heartbeatIntervalMs: 10000,
    queueDir: 'queue',
    logFile: 'bridge.log',
    heartbeatFile: 'heartbeat.json',
    claudeCommand: command || process.execPath,
    claudeArgs: args || [fx.fakeClaude, fx.knobs],
    laneArgs: {},
    projectDir: '..',
    maxRetries: 0,
    integrationBranch: 'dev',
    trunkBranch: 'main',
  }, null, 2));
}

function sliceFile(id, extra) {
  return [
    '---',
    `id: "${id}"`,
    `title: "Streamed session ${id}"`,
    'from: obrien',
    'to: rom',
    'lane: core',
    'references: null',
    ...(extra || []),
    '---',
    '',
    `# Streamed session ${id}`,
    '',
    'Body.',
    '',
  ].join('\n');
}

function doneReport(id) {
  return [
    '---',
    `id: "${id}"`,
    `title: "Streamed session ${id}"`,
    'from: rom',
    'to: nog',
    'status: DONE',
    `slice_id: "${id}"`,
    `branch: "slice/${id}"`,
    'completed: "2026-09-25T00:00:00.000Z"',
    'tokens_in: 0',
    'tokens_out: 0',
    'elapsed_ms: 0',
    'estimated_human_hours: 0.5',
    'compaction_occurred: false',
    '---',
    '',
    '## Summary',
    '',
    'Done.',
    '',
  ].join('\n');
}

/** Runs one Sam session end to end and returns everything it left behind. */
function runRom(fx, { steps, exitCode = 0, inactivityMs = 300000, slice, command, args, timeoutMs = 240000 }) {
  const id = fx.id;
  const inProgressPath = path.join(fx.queue, `${id}-IN_PROGRESS.md`);
  fs.writeFileSync(inProgressPath, slice || sliceFile(id));
  fs.writeFileSync(fx.knobs, JSON.stringify({ steps, exitCode }));
  writeConfig(fx, { command, args });
  fs.writeFileSync(fx.job, JSON.stringify({
    role: 'rom',
    work: fx.work,
    id,
    inProgressPath,
    donePath: path.join(fx.queue, `${id}-DONE.md`),
    errorPath: path.join(fx.queue, `${id}-ERROR.md`),
    inactivityMs,
    title: `Streamed session ${id}`,
    goal: 'stream it',
    memFile: fx.mem,
  }));

  const proc = spawnSync(process.execPath, [fx.driver, fx.job], {
    cwd: fx.work, encoding: 'utf8', timeout: timeoutMs,
    env: { ...process.env, ...GIT_ENV, NO_COLOR: '1' },
    maxBuffer: 64 * 1024 * 1024,
  });
  return { proc, ...readBack(fx, id) };
}

function readBack(fx, id) {
  const read = (p) => { try { return fs.readFileSync(p, 'utf8'); } catch (_) { return null; } };
  const events = (read(fx.register) || '').split('\n').filter(Boolean)
    .map((l) => { try { return JSON.parse(l); } catch (_) { return null; } })
    .filter((e) => e && String(e.slice_id || e.id || '') === String(id));
  return {
    events,
    eventsOf: (name) => events.filter((e) => e.event === name),
    logPath: path.join(fx.logs, `rom-${id}.log`),
    log: () => read(path.join(fx.logs, `rom-${id}.log`)),
    timing: () => { const t = read(path.join(fx.logs, `rom-${id}.timing.json`)); return t ? JSON.parse(t) : null; },
    errorFile: read(path.join(fx.queue, `${id}-ERROR.md`)),
    errorJson: (() => { const t = read(path.join(fx.errors, `${id}-ERROR.json`)); return t ? JSON.parse(t) : null; })(),
    doneFile: read(path.join(fx.queue, `${id}-DONE.md`)),
    parked: read(path.join(fx.queue, `${id}-PARKED.md`)),
    queued: read(path.join(fx.queue, `${id}-QUEUED.md`)),
    memory: (() => { const t = read(fx.mem); return t ? JSON.parse(t) : null; })(),
  };
}

const fm = (text, key) => {
  const m = String(text || '').match(new RegExp(`^${key}:\\s*(.*)$`, 'm'));
  return m ? m[1].trim().replace(/^"|"$/g, '') : null;
};

const sha256 = (buf) => crypto.createHash('sha256').update(buf).digest('hex');

/** The steps a session takes to look like a finished build: a commit and a report. */
const finishSteps = (id) => ([
  { op: 'commit', file: 'product.txt', content: `built by ${id}\n`, message: `slice ${id}: product change` },
  { op: 'done', id, content: doneReport(id) },
]);

const resultLine = (over) => ({
  type: 'result',
  subtype: 'success',
  session_id: 'sess-streamed-1',
  total_cost_usd: 4.2424242,
  usage: { input_tokens: 1234, output_tokens: 5678, cache_read_input_tokens: 999000 },
  ...over,
});

/** The Jordan side of the harness: a PARKED ticket, an EVALUATING report, one review. */
function runNog(fx, { steps, exitCode = 0, command, args, timeoutMs = 240000 }) {
  const id = fx.id;
  fs.writeFileSync(path.join(fx.queue, `${id}-PARKED.md`), sliceFile(id));
  fs.writeFileSync(path.join(fx.queue, `${id}-EVALUATING.md`), doneReport(id).replace(`branch: "slice/${id}"\n`, ''));
  fs.writeFileSync(fx.knobs, JSON.stringify({ steps, exitCode }));
  writeConfig(fx, { command, args });
  fs.writeFileSync(fx.job, JSON.stringify({ role: 'nog', work: fx.work, id, memFile: fx.mem }));

  const proc = spawnSync(process.execPath, [fx.driver, fx.job], {
    cwd: fx.work, encoding: 'utf8', timeout: timeoutMs,
    env: { ...process.env, ...GIT_ENV, NO_COLOR: '1' },
    maxBuffer: 64 * 1024 * 1024,
  });
  const back = readBack(fx, id);
  const nogLogPath = path.join(fx.logs, `nog-${id}-round1.log`);
  return {
    proc, ...back, nogLogPath,
    nogLog: () => { try { return fs.readFileSync(nogLogPath, 'utf8'); } catch (_) { return null; } },
    memory: back.memory,
  };
}

const nogVerdict = (id, verdict, summary) => [
  '---',
  `id: "${id}"`,
  `verdict: ${verdict}`,
  `summary: "${summary}"`,
  '---',
  '',
  '## Review',
  '',
  summary,
  '',
].join('\n');

/** stdout the test can reconstruct byte for byte: 64-byte ASCII units. */
const UNIT_OUT = 'sam-' + 'o'.repeat(59) + '\n';
const UNIT_ERR = 'sam-' + 'e'.repeat(59) + '\n';

function errorSections(text) {
  const m = String(text || '').match(/## stderr\n\n```\n([\s\S]*?)\n```\n\n## stdout\n\n```\n([\s\S]*)\n```$/);
  assert.ok(m, 'the ERROR file must still carry a stderr section and a stdout section');
  return { stderr: m[1], stdout: m[2] };
}

/** A timestamped tool run, so the attribution has real phases and seconds to find. */
function timedSession(sessionId) {
  const t0 = Date.parse('2026-09-25T10:00:00.000Z');
  const iso = (ms) => new Date(t0 + ms).toISOString();
  return [
    { type: 'system', subtype: 'init', session_id: sessionId, timestamp: iso(0) },
    { type: 'assistant', timestamp: iso(2000), message: { content: [{ type: 'tool_use', id: 'u1', name: 'Bash', input: { command: 'git log --oneline -5' } }] } },
    { type: 'user', timestamp: iso(5000), message: { content: [{ type: 'tool_result', tool_use_id: 'u1' }] } },
    { type: 'assistant', timestamp: iso(9000), message: { content: [{ type: 'tool_use', id: 'u2', name: 'Edit', input: { file_path: 'dashboard/app.js' } }] } },
    { type: 'user', timestamp: iso(14000), message: { content: [{ type: 'tool_result', tool_use_id: 'u2' }] } },
    { type: 'assistant', timestamp: iso(17000), message: { content: [{ type: 'tool_use', id: 'u3', name: 'Bash', input: { command: 'node --test regression/x.test.js' } }] } },
    { type: 'user', timestamp: iso(25000), message: { content: [{ type: 'tool_result', tool_use_id: 'u3' }] } },
  ].map((obj) => ({ op: 'line', obj }));
}

// ═══ slice-396-ac-1 ═════════════════════════════════════════════════════════

test('slice-396-ac-1 — a Sam session that writes more than 300 MB of stream-json finishes on its own, is recorded, and its log is its stdout', () => {
  const fx = buildFixture(nextId());
  try {
    const hashFile = path.join(fx.tmp, 'stdout-hash.json');
    const r = runRom(fx, {
      steps: [
        { op: 'line', obj: { type: 'system', subtype: 'init', session_id: 'sess-big-sam' } },
        { op: 'bulk', bytes: 300 * 1024 * 1024 },
        ...finishSteps(fx.id),
        { op: 'line', obj: resultLine() },
        { op: 'hash', file: hashFile },
      ],
    });

    assert.equal(r.proc.status, 0, 'the daemon process survives the session');
    const wrote = JSON.parse(fs.readFileSync(hashFile, 'utf8'));
    assert.ok(wrote.bytes > 300 * 1024 * 1024,
      `the session must actually write more than 300 MB (wrote ${wrote.bytes})`);

    // Not killed: no ERROR file, no ERROR event, and a DONE event instead.
    assert.equal(r.errorFile, null, 'a 300 MB session writes no ERROR file');
    assert.deepEqual(r.eventsOf('ERROR'), [], 'a 300 MB session writes no ERROR event');
    const done = r.eventsOf('DONE');
    assert.equal(done.length, 1, 'the run ends in exactly one DONE event');

    // The log IS the stdout — every byte of it, in order.
    const logBuf = fs.readFileSync(r.logPath);
    assert.equal(logBuf.length, wrote.bytes, 'the log holds every byte the session wrote');
    assert.equal(sha256(logBuf), wrote.sha256, 'the log is byte-identical to the session stdout');

    // And the numbers are the result line's, not an estimate.
    assert.equal(done[0].tokensIn, 1234);
    assert.equal(done[0].tokensOut, 5678);
    assert.equal(done[0].tokensCacheRead, 999000);
    assert.equal(done[0].costUsd, 4.2424242);
  } finally { dropFixture(fx); }
});

// ═══ slice-396-ac-2 ═════════════════════════════════════════════════════════

test('slice-396-ac-2 — a Jordan review that writes more than 300 MB of stream-json finishes, is recorded as REJECTED, and its log is its stdout', () => {
  const fx = buildFixture(nextId());
  try {
    const hashFile = path.join(fx.tmp, 'stdout-hash.json');
    const r = runNog(fx, {
      steps: [
        { op: 'line', obj: { type: 'system', subtype: 'init', session_id: 'sess-big-jordan' } },
        { op: 'bulk', bytes: 300 * 1024 * 1024 },
        { op: 'verdict', id: fx.id, content: nogVerdict(fx.id, 'REJECTED', 'The diff does not do what the brief asked') },
        { op: 'line', obj: resultLine({ session_id: 'sess-big-jordan', total_cost_usd: 1.7242135, usage: { input_tokens: 17, output_tokens: 1766, cache_read_input_tokens: 1045779 } }) },
        { op: 'hash', file: hashFile },
      ],
    });

    assert.equal(r.proc.status, 0, 'the daemon process survives the review');
    const wrote = JSON.parse(fs.readFileSync(hashFile, 'utf8'));
    assert.ok(wrote.bytes > 300 * 1024 * 1024,
      `the review must actually write more than 300 MB (wrote ${wrote.bytes})`);

    const decisions = r.eventsOf('NOG_DECISION');
    assert.equal(decisions.length, 1, 'the round ends in exactly one NOG_DECISION');
    assert.equal(decisions[0].verdict, 'REJECTED');
    assert.notEqual(decisions[0].reason, 'verdict_unreadable',
      'a 300 MB review that wrote a verdict is not an unreadable one');
    assert.equal(decisions[0].tokensIn, 17);
    assert.equal(decisions[0].tokensOut, 1766);
    assert.equal(decisions[0].tokensCacheRead, 1045779);
    assert.equal(decisions[0].costUsd, 1.7242135);

    const logBuf = fs.readFileSync(r.nogLogPath);
    assert.equal(logBuf.length, wrote.bytes, "the reviewer's log holds every byte the session wrote");
    assert.equal(sha256(logBuf), wrote.sha256, "the reviewer's log is byte-identical to its stdout");
  } finally { dropFixture(fx); }
});

// ═══ slice-396-ac-3 ═════════════════════════════════════════════════════════

test('slice-396-ac-3 — 300 MB streams past the orchestrator without 64 MB of its memory', () => {
  const fx = buildFixture(nextId());
  try {
    const r = runRom(fx, {
      steps: [
        { op: 'line', obj: { type: 'system', subtype: 'init', session_id: 'sess-mem' } },
        { op: 'bulk', bytes: 300 * 1024 * 1024 },
        ...finishSteps(fx.id),
        { op: 'line', obj: resultLine() },
      ],
    });
    assert.equal(r.proc.status, 0);
    assert.equal(r.eventsOf('DONE').length, 1, 'the session ran to its end');
    assert.ok(r.memory, 'the driver recorded its own memory');
    assert.ok(r.memory.peakDeltaBytes < 64 * 1024 * 1024,
      `heapUsed + arrayBuffers rose ${Math.round(r.memory.peakDeltaBytes / 1048576)} MB above the session's start — the buffer is back`);
  } finally { dropFixture(fx); }
});

// ═══ slice-396-ac-4 ═════════════════════════════════════════════════════════

test("slice-396-ac-4 — every value Sam's run records equals what the session's whole stdout gives", () => {
  // The oracle is the log: it is the whole stdout, so the functions that used to be
  // handed the whole stdout are run over it here and compared with what was recorded.
  const cases = [
    { name: 'a normal session', pre: [], result: resultLine({ session_id: 'sess-normal' }) },
    { name: 'a session over 1 MB', pre: [{ op: 'bulk', bytes: 2 * 1024 * 1024 }], result: resultLine({ session_id: 'sess-big' }) },
    { name: 'a session with no result line', pre: [], result: null },
    { name: 'a session whose result line is longer than 64 KB', pre: [], result: resultLine({ session_id: 'sess-fat', pad: 'y'.repeat(70000) }) },
  ];

  for (const c of cases) {
    const fx = buildFixture(nextId());
    try {
      // No result event: the last JSON object on the stream is what the numbers
      // have always fallen back to, and it carries a usage block of its own.
      const noResultTail = {
        op: 'line',
        obj: {
          type: 'assistant',
          session_id: 'sess-noresult',
          timestamp: '2026-09-25T10:00:30.000Z',
          usage: { input_tokens: 11, output_tokens: 22, cache_read_input_tokens: 33 },
          message: { content: [{ type: 'text', text: 'done' }] },
        },
      };
      const tail = c.result ? [{ op: 'line', obj: c.result }] : [noResultTail];

      const r = runRom(fx, {
        steps: [...timedSession(`sess-${fx.id}`), ...c.pre, ...finishSteps(fx.id), ...tail],
      });
      assert.equal(r.proc.status, 0, `${c.name}: the daemon survives`);

      const whole = r.log();
      assert.ok(whole && whole.length > 0, `${c.name}: the log is the whole stdout`);

      const oracleTelemetry = liveOrch.sessionTelemetry(whole, 0);
      const oracleTiming = attributeRun(whole);
      const oracleSession = liveOrch.extractSessionId(whole);

      // 1 · the DONE report's four numbers
      assert.equal(Number(fm(r.doneFile, 'tokens_in')), oracleTelemetry.tokensIn, `${c.name}: report tokens_in`);
      assert.equal(Number(fm(r.doneFile, 'tokens_out')), oracleTelemetry.tokensOut, `${c.name}: report tokens_out`);
      assert.equal(Number(fm(r.doneFile, 'tokens_cache_read')), oracleTelemetry.tokensCacheRead, `${c.name}: report tokens_cache_read`);
      assert.equal(Number(fm(r.doneFile, 'cost_usd')), oracleTelemetry.costUsd, `${c.name}: report cost_usd`);

      // 2 · the DONE register event's numbers and its split
      const done = r.eventsOf('DONE');
      assert.equal(done.length, 1, `${c.name}: one DONE event`);
      assert.equal(done[0].tokensIn, oracleTelemetry.tokensIn, `${c.name}: event tokensIn`);
      assert.equal(done[0].tokensOut, oracleTelemetry.tokensOut, `${c.name}: event tokensOut`);
      assert.equal(done[0].tokensCacheRead, oracleTelemetry.tokensCacheRead, `${c.name}: event tokensCacheRead`);
      assert.equal(done[0].costUsd, oracleTelemetry.costUsd, `${c.name}: event costUsd`);
      assert.deepEqual(done[0].phases, oracleTiming.phases, `${c.name}: event phases`);
      assert.equal(done[0].calls, oracleTiming.calls, `${c.name}: event calls`);
      assert.equal(done[0].first_product_edit_s, oracleTiming.first_product_edit_s, `${c.name}: event first_product_edit_s`);

      // The split must have something in it, or the comparison above proves nothing.
      assert.ok(oracleTiming.calls >= 3, `${c.name}: the fixture session makes real tool calls`);
      assert.ok(oracleTiming.first_product_edit_s != null, `${c.name}: the fixture session edits a product file`);

      // 3 · the sidecar
      assert.deepEqual(r.timing(), oracleTiming, `${c.name}: rom-<id>.timing.json`);

      // 4 · the session id on the parked ticket
      assert.equal(fm(r.parked, 'rom_session_id'), oracleSession, `${c.name}: rom_session_id`);
    } finally { dropFixture(fx); }
  }

  // 5 · actualTokensOut on a verification failure — a report with no commit behind it.
  const fx = buildFixture(nextId());
  try {
    const r = runRom(fx, {
      steps: [
        ...timedSession('sess-nocommit'),
        { op: 'done', id: fx.id, content: doneReport(fx.id) },
        { op: 'line', obj: resultLine({ session_id: 'sess-nocommit' }) },
      ],
    });
    const whole = r.log();
    const oracle = liveOrch.sessionTelemetry(whole, 0);
    const errs = r.eventsOf('ERROR');
    assert.equal(errs.length, 1, 'a report with no commits behind it is one ERROR event');
    assert.equal(errs[0].reason, 'rom_no_commits');
    assert.equal(errs[0].actualTokensOut, oracle.tokensOut,
      'actualTokensOut is the session\'s own output tokens, not an estimate');
  } finally { dropFixture(fx); }
});

// ═══ slice-396-ac-5 ═════════════════════════════════════════════════════════

test("slice-396-ac-5 — a failed Sam session's ERROR file reads as today, with stdout and stderr bounded", () => {
  // ── a crash whose output fits inside the bound ───────────────────────────
  {
    const fx = buildFixture(nextId());
    try {
      const outUnits = 100;   // 6,400 bytes
      const errUnits = 50;    // 3,200 bytes
      const r = runRom(fx, {
        exitCode: 1,
        steps: [
          { op: 'pattern', stream: 'stdout', unit: UNIT_OUT, count: outUnits },
          { op: 'pattern', stream: 'stderr', unit: UNIT_ERR, count: errUnits },
        ],
      });
      const fullOut = UNIT_OUT.repeat(outUnits);
      const fullErr = UNIT_ERR.repeat(errUnits);

      assert.equal(fm(r.errorFile, 'reason'), 'crash');
      assert.equal(fm(r.errorFile, 'exit_code'), '1', 'exit code 1 reaches the frontmatter');
      assert.ok(r.errorFile.includes('- Exit code: 1'), 'and the invocation details');
      const sections = errorSections(r.errorFile);
      assert.equal(sections.stdout, fullOut, 'the whole stdout, under the bound');
      assert.equal(sections.stderr, fullErr, 'the whole stderr, under the bound');

      const errs = r.eventsOf('ERROR');
      assert.equal(errs.length, 1);
      assert.equal(errs[0].reason, 'crash');
      assert.equal(errs[0].exit_code, 1, 'the register event carries the exit code');
      assert.equal(errs[0].stderr_tail, fullErr.slice(-2000), 'stderr_tail is the last 2,000 characters');
      assert.equal(r.errorJson.lastOutput, (fullOut + fullErr).slice(-2000),
        'lastOutput is the last 2,000 characters of stdout followed by stderr');
    } finally { dropFixture(fx); }
  }

  // ── a crash that writes far more than the bound ──────────────────────────
  {
    const fx = buildFixture(nextId());
    try {
      const outUnits = 4000;  // 256,000 bytes
      const errUnits = 3000;  // 192,000 bytes
      const r = runRom(fx, {
        exitCode: 1,
        steps: [
          { op: 'pattern', stream: 'stdout', unit: UNIT_OUT, count: outUnits },
          { op: 'pattern', stream: 'stderr', unit: UNIT_ERR, count: errUnits },
        ],
      });
      const fullOut = UNIT_OUT.repeat(outUnits);
      const fullErr = UNIT_ERR.repeat(errUnits);
      const sections = errorSections(r.errorFile);
      assert.equal(Buffer.byteLength(sections.stdout), TAIL, 'exactly the last 65,536 bytes of stdout');
      assert.equal(sections.stdout, fullOut.slice(-TAIL), 'and they are the LAST ones');
      assert.equal(Buffer.byteLength(sections.stderr), TAIL, 'exactly the last 65,536 bytes of stderr');
      assert.equal(sections.stderr, fullErr.slice(-TAIL), 'and they are the LAST ones');
      assert.equal(r.eventsOf('ERROR')[0].stderr_tail, fullErr.slice(-2000));
      assert.equal(r.errorJson.lastOutput, (fullOut.slice(-TAIL) + fullErr.slice(-TAIL)).slice(-2000));
    } finally { dropFixture(fx); }
  }

  // ── a session that stops talking ─────────────────────────────────────────
  // The inactivity sweep runs every 30s, so the session has to be silent across one.
  {
    const fx = buildFixture(nextId());
    try {
      const r = runRom(fx, {
        inactivityMs: 1000,
        steps: [
          { op: 'line', obj: { type: 'system', subtype: 'init', session_id: 'sess-silent' } },
          { op: 'sleep', ms: 90000 },
        ],
        timeoutMs: 120000,
      });
      assert.equal(fm(r.errorFile, 'reason'), 'inactivity_timeout');
      assert.ok(r.errorFile.includes('- Signal: SIGTERM'), 'the file records the signal it was killed with');
      assert.equal(r.eventsOf('ERROR')[0].reason, 'inactivity_timeout');
      const sections = errorSections(r.errorFile);
      assert.ok(sections.stdout.includes('sess-silent'), 'what it did say is still in the file');
    } finally { dropFixture(fx); }
  }

  // ── a session that exits clean with no report: tails stay at 500 ─────────
  {
    const fx = buildFixture(nextId());
    try {
      const outUnits = 4000;
      const r = runRom(fx, {
        steps: [
          { op: 'commit', file: 'product.txt', content: 'half a change\n', message: 'wip' },
          { op: 'dirty', file: 'product.txt', content: 'half a change, uncommitted\n' },
          { op: 'pattern', stream: 'stdout', unit: UNIT_OUT, count: outUnits },
          { op: 'pattern', stream: 'stderr', unit: UNIT_ERR, count: outUnits },
        ],
      });
      const fullOut = UNIT_OUT.repeat(outUnits);
      const fullErr = UNIT_ERR.repeat(outUnits);
      assert.match(fm(r.errorFile, 'reason'), /^rom_self_terminated_/);
      const sections = errorSections(r.errorFile);
      assert.equal(sections.stdout, '…' + fullOut.slice(-500), 'a self-terminated report keeps its 500-character tail');
      assert.equal(sections.stderr, '…' + fullErr.slice(-500));

      const rescue = fs.readFileSync(path.join(fx.work, 'bridge', 'worktree-rescue', String(fx.id), 'RESCUE.md'), 'utf8');
      assert.ok(rescue.includes('…' + fullOut.slice(-500)), 'RESCUE.md keeps its 500-character stdout tail');
      assert.ok(rescue.includes('…' + fullErr.slice(-500)), 'RESCUE.md keeps its 500-character stderr tail');
    } finally { dropFixture(fx); }
  }
});

// ═══ slice-396-ac-6 ═════════════════════════════════════════════════════════

test('slice-396-ac-6 — a rate limit is read from the whole session, and the pause length from its last 64 KB', () => {
  const BULK = 300 * 1024;   // pushes anything before it well past 64 KB from the end

  // ── "hit your limit", 300 KB before the end, with a reset time in the tail ──
  {
    const fx = buildFixture(nextId());
    try {
      const r = runRom(fx, {
        exitCode: 1,
        steps: [
          { op: 'raw', text: '{"type":"system","text":"You have hit your limit. It resets 4am (Asia/Nicosia)"}\n' },
          { op: 'bulk', bytes: BULK },
          { op: 'raw', text: 'Claude usage limit reached — resets 4am (Asia/Nicosia)\n' },
        ],
      });
      assert.equal(r.errorFile, null, 'a rate limit writes no ERROR file');
      assert.ok(r.queued, 'the slice goes back to QUEUED');
      const limited = r.eventsOf('RATE_LIMITED');
      assert.equal(limited.length, 1, 'one RATE_LIMITED event');

      // The reset the daemon computes today, plus its one-minute buffer.
      const tz = 'Asia/Nicosia';
      const localDate = new Intl.DateTimeFormat('en-CA', { timeZone: tz, year: 'numeric', month: '2-digit', day: '2-digit' }).format(new Date());
      const utcMs = Date.parse(`${localDate}T04:00:00`);
      const resetMs = utcMs > Date.now() ? utcMs : utcMs + 86400000;
      const expected = (resetMs - Date.now()) + 60000;
      assert.ok(Math.abs(limited[0].waitMs - expected) <= 5000,
        `waitMs ${limited[0].waitMs} should be within 5s of ${expected}`);
    } finally { dropFixture(fx); }
  }

  // ── a REJECTED rate_limit_event, 300 KB before the end, no reset text at all ──
  {
    const fx = buildFixture(nextId());
    try {
      const r = runRom(fx, {
        exitCode: 1,
        steps: [
          { op: 'raw', text: '{"type":"system","subtype":"rate_limit_event","rate_limit":{"status":"rejected"}}\n' },
          { op: 'raw', text: 'resets 4am (Asia/Nicosia) — but this is not in the last 64 KB\n' },
          { op: 'bulk', bytes: BULK },
        ],
      });
      assert.equal(r.errorFile, null, 'a rejected rate-limit event writes no ERROR file');
      assert.ok(r.queued, 'the slice goes back to QUEUED');
      const limited = r.eventsOf('RATE_LIMITED');
      assert.equal(limited.length, 1);
      assert.equal(limited[0].waitMs, 3600000,
        'with no reset time in the last 64 KB the pause is the one-hour default, even though earlier stdout carried one');
    } finally { dropFixture(fx); }
  }

  // ── warnings are not limits ───────────────────────────────────────────────
  {
    const fx = buildFixture(nextId());
    try {
      const r = runRom(fx, {
        exitCode: 1,
        steps: [
          { op: 'raw', text: '{"type":"system","subtype":"rate_limit_event","rate_limit":{"status":"allowed"}}\n' },
          { op: 'raw', text: '{"type":"system","subtype":"rate_limit_event","rate_limit":{"status":"allowed_warning","overageStatus":"rejected"}}\n' },
          { op: 'bulk', bytes: BULK },
        ],
      });
      assert.deepEqual(r.eventsOf('RATE_LIMITED'), [], 'approaching a limit is not hitting one');
      const errs = r.eventsOf('ERROR');
      assert.equal(errs.length, 1);
      assert.equal(errs[0].reason, 'crash');
      assert.equal(fm(r.errorFile, 'reason'), 'crash');
    } finally { dropFixture(fx); }
  }
});

// ═══ slice-396-ac-7 ═════════════════════════════════════════════════════════

test('slice-396-ac-7 — an API error anywhere in the session requeues the slice until three retries are spent', () => {
  const BULK = 300 * 1024;

  // ── first failure: requeued ──────────────────────────────────────────────
  {
    const fx = buildFixture(nextId());
    try {
      const r = runRom(fx, {
        exitCode: 1,
        steps: [
          { op: 'raw', text: '{"type":"system","subtype":"api_error","message":"upstream"}\n' },
          { op: 'bulk', bytes: BULK },
        ],
      });
      assert.equal(r.errorFile, null, 'a retryable API error writes no ERROR file');
      assert.ok(r.queued, 'the slice goes back to QUEUED');
      assert.equal(fm(r.queued, 'status'), 'QUEUED');
      assert.equal(fm(r.queued, '_api_retry_count'), '1', 'the retry count is raised by one');
      const retries = r.eventsOf('API_RETRY');
      assert.equal(retries.length, 1);
      assert.equal(retries[0].retryCount, 1);
    } finally { dropFixture(fx); }
  }

  // ── the fourth: filed as a crash ─────────────────────────────────────────
  {
    const fx = buildFixture(nextId());
    try {
      const r = runRom(fx, {
        exitCode: 1,
        slice: sliceFile(fx.id, ['_api_retry_count: "3"']),
        steps: [
          { op: 'raw', text: 'API Error: 529 overloaded\n' },
          { op: 'bulk', bytes: BULK },
        ],
      });
      assert.deepEqual(r.eventsOf('API_RETRY'), [], 'three retries are all there are');
      const errs = r.eventsOf('ERROR');
      assert.equal(errs.length, 1);
      assert.equal(errs[0].reason, 'crash');
    } finally { dropFixture(fx); }
  }
});

// ═══ slice-396-ac-8 ═════════════════════════════════════════════════════════

test('slice-396-ac-8 — the session log is written while the session runs and never rewritten when it ends', async () => {
  // ── a line reaches the log within a second, while the session is still going ──
  {
    const fx = buildFixture(nextId());
    try {
      const stampFile = path.join(fx.tmp, 'stamp.txt');
      const id = fx.id;
      const inProgressPath = path.join(fx.queue, `${id}-IN_PROGRESS.md`);
      fs.writeFileSync(inProgressPath, sliceFile(id));
      fs.writeFileSync(fx.knobs, JSON.stringify({
        exitCode: 0,
        steps: [
          { op: 'sleep', ms: 500 },
          { op: 'raw', text: '{"type":"assistant","marker":"LIVE-LOG-MARKER"}\n' },
          { op: 'stamp', file: stampFile },
          { op: 'sleep', ms: 8000 },
          ...finishSteps(id),
          { op: 'line', obj: resultLine() },
        ],
      }));
      writeConfig(fx);
      fs.writeFileSync(fx.job, JSON.stringify({
        role: 'rom', work: fx.work, id, inProgressPath,
        donePath: path.join(fx.queue, `${id}-DONE.md`),
        errorPath: path.join(fx.queue, `${id}-ERROR.md`),
        inactivityMs: 300000, title: 't', goal: 'g', memFile: fx.mem,
      }));

      const child = spawn(process.execPath, [fx.driver, fx.job], {
        cwd: fx.work, env: { ...process.env, ...GIT_ENV, NO_COLOR: '1' }, stdio: 'ignore',
      });
      const logPath = path.join(fx.logs, `rom-${id}.log`);
      let seenAt = null;
      const deadline = Date.now() + 20000;
      while (Date.now() < deadline && seenAt === null) {
        try {
          if (fs.readFileSync(logPath, 'utf8').includes('LIVE-LOG-MARKER')) seenAt = Date.now();
        } catch (_) {}
        if (seenAt === null) await new Promise((r) => setTimeout(r, 25));
      }
      const stillRunning = child.exitCode === null;
      await new Promise((resolve) => child.on('close', resolve));

      assert.ok(seenAt !== null, 'the line reached the log while the session was still running');
      assert.ok(stillRunning, 'and the session had not ended yet — this is the live log, not the post-mortem');
      const wroteAt = Number(fs.readFileSync(stampFile, 'utf8'));
      assert.ok(seenAt - wroteAt <= 1000, `the line took ${seenAt - wroteAt}ms to reach the log`);
    } finally { dropFixture(fx); }
  }

  // ── stripping the stderr inserts leaves exactly the stdout ───────────────
  {
    const fx = buildFixture(nextId());
    try {
      const errChunks = ['[warn] one\n', '[warn] two\n', '[warn] three\n'];
      const outChunks = [
        '{"type":"assistant","n":1}\n',
        '{"type":"assistant","n":2}\n',
        '{"type":"assistant","n":3}\n',
        '{"type":"assistant","n":4}\n',
      ];
      const r = runRom(fx, {
        steps: [
          { op: 'raw', text: outChunks[0] }, { op: 'sleep', ms: 80 },
          { op: 'stderr', text: errChunks[0] }, { op: 'sleep', ms: 80 },
          { op: 'raw', text: outChunks[1] }, { op: 'sleep', ms: 80 },
          { op: 'stderr', text: errChunks[1] }, { op: 'sleep', ms: 80 },
          { op: 'stderr', text: errChunks[2] }, { op: 'sleep', ms: 80 },
          { op: 'raw', text: outChunks[2] }, { op: 'sleep', ms: 80 },
          ...finishSteps(fx.id),
          { op: 'raw', text: outChunks[3] },
        ],
      });
      let log = r.log();
      assert.ok(log, 'the log exists');
      for (const chunk of errChunks) {
        const insert = '[stderr] ' + chunk;
        const at = log.indexOf(insert);
        assert.ok(at >= 0, `the log carries one "[stderr] " insert per stderr chunk (${JSON.stringify(chunk)})`);
        log = log.slice(0, at) + log.slice(at + insert.length);
      }
      assert.equal(log, outChunks.join(''),
        'with the inserts removed the log is exactly the stdout, byte for byte and in order');
    } finally { dropFixture(fx); }
  }

  // ── Jordan's log has no end-of-run rewrite in it ─────────────────────────
  {
    const fx = buildFixture(nextId());
    try {
      const r = runNog(fx, {
        steps: [
          { op: 'raw', text: '{"type":"assistant","n":1}\n' },
          { op: 'stderr', text: 'a note on stderr\n' },
          { op: 'verdict', id: fx.id, content: nogVerdict(fx.id, 'REJECTED', 'Findings') },
          { op: 'line', obj: resultLine({ session_id: 'sess-nog-log' }) },
        ],
      });
      const log = r.nogLog();
      assert.ok(log, "the reviewer's log exists");
      assert.ok(!log.includes('--- stderr ---'),
        "the reviewer's log is never rewritten with a stderr block at the end");
      assert.ok(log.includes('[stderr] a note on stderr'),
        'stderr is teed where it arrived instead');
    } finally { dropFixture(fx); }
  }
});

// ═══ slice-396-ac-9 ═════════════════════════════════════════════════════════

test("slice-396-ac-9 — Jordan's review numbers equal what his whole stdout gives, and a crashed review is still an unreadable verdict", () => {
  // ── a verdict, with a result line longer than 64 KB ──────────────────────
  {
    const fx = buildFixture(nextId());
    try {
      const r = runNog(fx, {
        steps: [
          { op: 'line', obj: { type: 'system', subtype: 'init', session_id: 'sess-nog-fat' } },
          { op: 'verdict', id: fx.id, content: nogVerdict(fx.id, 'REJECTED', 'Findings') },
          { op: 'line', obj: resultLine({ session_id: 'sess-nog-fat', pad: 'z'.repeat(70000), total_cost_usd: 0.55, usage: { input_tokens: 7, output_tokens: 8, cache_read_input_tokens: 9 } }) },
        ],
      });
      const oracle = liveOrch.reviewTelemetry(r.nogLog());
      assert.deepEqual(oracle, { tokensIn: 7, tokensOut: 8, tokensCacheRead: 9, costUsd: 0.55 },
        'the whole stdout gives these four numbers');
      const decision = r.eventsOf('NOG_DECISION')[0];
      assert.ok(decision, 'the round ends on a NOG_DECISION');
      assert.equal(decision.verdict, 'REJECTED');
      assert.equal(decision.tokensIn, oracle.tokensIn);
      assert.equal(decision.tokensOut, oracle.tokensOut);
      assert.equal(decision.tokensCacheRead, oracle.tokensCacheRead);
      assert.equal(decision.costUsd, oracle.costUsd);
    } finally { dropFixture(fx); }
  }

  // ── no result line: no numbers at all, and none estimated ────────────────
  {
    const fx = buildFixture(nextId());
    try {
      const r = runNog(fx, {
        steps: [
          { op: 'line', obj: { type: 'assistant', session_id: 'sess-nog-killed', usage: { input_tokens: 5, output_tokens: 6 }, message: { content: [{ type: 'text', text: 'mid-turn' }] } } },
          { op: 'verdict', id: fx.id, content: nogVerdict(fx.id, 'REJECTED', 'Findings') },
        ],
      });
      const decision = r.eventsOf('NOG_DECISION')[0];
      assert.ok(decision, 'the round still ends on a NOG_DECISION');
      for (const key of ['tokensIn', 'tokensOut', 'tokensCacheRead', 'costUsd']) {
        assert.ok(!(key in decision), `a review with no result event writes no ${key}`);
      }
    } finally { dropFixture(fx); }
  }

  // ── a review that exits non-zero ─────────────────────────────────────────
  {
    const fx = buildFixture(nextId());
    try {
      const r = runNog(fx, {
        exitCode: 1,
        steps: [{ op: 'raw', text: '{"type":"assistant","n":1}\n' }],
      });
      const decision = r.eventsOf('NOG_DECISION')[0];
      assert.ok(decision, 'a crashed review still closes its round');
      assert.equal(decision.verdict, 'REJECTED');
      assert.equal(decision.reason, 'verdict_unreadable');
    } finally { dropFixture(fx); }
  }
});

// ═══ traps ══════════════════════════════════════════════════════════════════

test('J-session-streamed — trap 1: a line split across two chunks, and a character split inside it, survive', () => {
  // ── a result line written in two writes, cut inside a multi-byte character ──
  {
    const fx = buildFixture(nextId());
    try {
      const marker = 'héllo 🜂 wörld';
      const line = Buffer.from(JSON.stringify(resultLine({ session_id: 'sess-split', pad: marker })) + '\n', 'utf8');
      // Cut inside the four bytes of 🜂, so neither half is valid UTF-8 on its own.
      const cut = line.indexOf(Buffer.from('🜂', 'utf8')) + 2;
      const hashFile = path.join(fx.tmp, 'stdout-hash.json');
      const r = runRom(fx, {
        steps: [
          { op: 'line', obj: { type: 'system', subtype: 'init', session_id: 'sess-split' } },
          ...finishSteps(fx.id),
          { op: 'rawBytes', bytes: Array.from(line.subarray(0, cut)) },
          { op: 'sleep', ms: 120 },
          { op: 'rawBytes', bytes: Array.from(line.subarray(cut)) },
          { op: 'hash', file: hashFile },
        ],
      });
      const done = r.eventsOf('DONE');
      assert.equal(done.length, 1, 'a result line written in two writes is still a result line');
      assert.equal(done[0].tokensOut, 5678, 'and its numbers are read off it');
      assert.equal(done[0].costUsd, 4.2424242);

      const logBuf = fs.readFileSync(r.logPath);
      const wrote = JSON.parse(fs.readFileSync(hashFile, 'utf8'));
      assert.equal(sha256(logBuf), wrote.sha256, 'the log is byte-identical to the stdout across the cut');
      assert.ok(logBuf.toString('utf8').includes(marker), 'the split character reaches the log whole');
      assert.equal(fm(r.parked, 'rom_session_id'), 'sess-split', 'and the id on that line is read off it');
    } finally { dropFixture(fx); }
  }

  // ── "hit your limit", written in two parts with a pause in between ───────
  {
    const fx = buildFixture(nextId());
    try {
      const r = runRom(fx, {
        exitCode: 1,
        steps: [
          { op: 'raw', text: 'You have hit yo' },
          { op: 'sleep', ms: 120 },
          { op: 'raw', text: 'ur limit for today\n' },
        ],
      });
      assert.equal(r.eventsOf('RATE_LIMITED').length, 1,
        'a limit message split across two chunks is still a limit message');
      assert.equal(r.errorFile, null);
    } finally { dropFixture(fx); }
  }

  // ── a rejected rate_limit_event, written in two parts with a pause ───────
  {
    const fx = buildFixture(nextId());
    try {
      const r = runRom(fx, {
        exitCode: 1,
        steps: [
          { op: 'raw', text: '{"type":"system","subtype":"rate_limit_event","rate_limit":{"sta' },
          { op: 'sleep', ms: 120 },
          { op: 'raw', text: 'tus":"rejected"}}\n' },
        ],
      });
      assert.equal(r.eventsOf('RATE_LIMITED').length, 1,
        'a rejected rate-limit event split across two chunks is still rejected');
      assert.equal(r.errorFile, null);
    } finally { dropFixture(fx); }
  }
});

test('J-session-streamed — trap 2: the whole prompt still reaches the session on stdin', () => {
  const fx = buildFixture(nextId());
  try {
    const stdinFile = path.join(fx.tmp, 'stdin.txt');
    const slice = sliceFile(fx.id);
    const r = runRom(fx, {
      slice,
      steps: [
        { op: 'stdin', file: stdinFile },
        ...finishSteps(fx.id),
        { op: 'line', obj: resultLine() },
      ],
    });
    assert.equal(r.eventsOf('DONE').length, 1, 'the session ran');

    const received = fs.readFileSync(stdinFile);
    const stamped = received.toString('utf8').match(/^completed: "([^"]+)"$/m);
    assert.ok(stamped, 'the prompt carries the template the daemon stamps');
    const expected = slice + liveOrch.buildDoneTemplate({
      id: fx.id,
      worktreeDonePath: path.join(WORKTREE_BASE, String(fx.id), 'bridge', 'queue', `${fx.id}-DONE.md`),
      sliceBranch: `slice/${fx.id}`,
      sliceContent: slice,
      lane: 'core',
    }).replace(/^completed: "[^"]+"$/m, `completed: "${stamped[1]}"`);
    assert.ok(received.length > 0, 'the session received something on stdin — not an empty prompt');
    assert.equal(received.length, Buffer.byteLength(expected),
      'the session received every byte of the prompt');
    assert.equal(received.toString('utf8'), expected, 'and it is the prompt the daemon built');
  } finally { dropFixture(fx); }
});

test('J-session-streamed — trap 3: a command that cannot be started is one ERROR, not a dead daemon', () => {
  // ── Sam ──────────────────────────────────────────────────────────────────
  {
    const fx = buildFixture(nextId());
    try {
      const r = runRom(fx, {
        command: path.join(fx.tmp, 'no-such-claude'),
        args: [],
        steps: [],
      });
      assert.equal(r.proc.status, 0, 'the daemon process survives a command it cannot start');
      const errs = r.eventsOf('ERROR');
      assert.equal(errs.length, 1, 'exactly one ERROR event');
      assert.equal(errs[0].reason, 'crash');
      assert.ok(r.errorFile, 'exactly one ERROR file');
      assert.equal(fm(r.errorFile, 'reason'), 'crash');
      assert.equal(fm(r.errorFile, 'exit_code'), 'ENOENT', 'the spawn failure keeps its own code');
    } finally { dropFixture(fx); }
  }

  // ── Jordan ───────────────────────────────────────────────────────────────
  {
    const fx = buildFixture(nextId());
    try {
      const r = runNog(fx, {
        command: path.join(fx.tmp, 'no-such-claude'),
        args: [],
        steps: [],
      });
      assert.equal(r.proc.status, 0, 'the daemon process survives it on the review side too');
      const decisions = r.eventsOf('NOG_DECISION');
      assert.equal(decisions.length, 1, 'one round, closed');
      assert.equal(decisions[0].verdict, 'REJECTED');
      assert.equal(decisions[0].reason, 'verdict_unreadable');
    } finally { dropFixture(fx); }
  }
});

test('J-session-streamed — trap 4: the tracked child is the real process, so pause, resume and abort still reach it', async () => {
  // The dashboard's three controls signal activeChildren through .pid and read
  // .exitCode. What invokeRom puts there is what streamSession returns.
  assert.match(ORCH_SRC, /const child = streamSession\(/,
    'invokeRom must keep the child the session helper returns');
  assert.match(ORCH_SRC, /activeChildren\.set\(String\(id\), \{ child, worktreePath \}\);/,
    'and that child is what pause/resume/abort are given');

  const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'j-session-streamed-signals-'));
  tmpDirs.push(tmp);
  const script = path.join(tmp, 'talker.js');
  fs.writeFileSync(script, `
    let n = 0;
    setInterval(() => { process.stdout.write('{"type":"assistant","tick":' + (n++) + '}\\n'); }, 50);
  `);
  const logPath = path.join(tmp, 'session.log');

  const closed = new Promise((resolve) => {
    const child = streamSession(
      { command: process.execPath, args: [script], cwd: tmp, prompt: 'go', logPath },
      (outcome) => resolve({ outcome, child }),
    );

    assert.equal(typeof child.pid, 'number', 'the helper returns a real child process');
    assert.equal(child.exitCode, null, 'which reads as alive while it runs');

    const size = () => { try { return fs.statSync(logPath).size; } catch (_) { return 0; } };
    const wait = (ms) => new Promise((r) => setTimeout(r, ms));

    (async () => {
      await wait(400);
      assert.ok(size() > 0, 'the session is talking');

      process.kill(child.pid, 'SIGSTOP');
      await wait(300);
      const paused = size();
      await wait(400);
      assert.equal(size(), paused, 'pausing the tracked child stops its output');

      process.kill(child.pid, 'SIGCONT');
      await wait(400);
      assert.ok(size() > paused, 'resuming it starts the output again');

      process.kill(child.pid, 'SIGKILL');
    })();
  });

  const { outcome, child } = await closed;
  assert.equal(outcome.signal, 'SIGKILL', 'abort ends the process');
  assert.notEqual(child.exitCode === null && child.signalCode === null, true,
    'and the entry reads as finished afterwards');
});

test('J-session-streamed — trap 5: a session that writes only to stderr is not killed for inactivity', () => {
  // Output is what keeps a session alive, and the sweep runs every 30s — so the
  // session has to talk across one while saying nothing at all on stdout.
  const fx = buildFixture(nextId());
  try {
    const r = runRom(fx, {
      inactivityMs: 1000,
      timeoutMs: 120000,
      steps: [
        { op: 'repeat', stream: 'stderr', ms: 500, count: 76, text: 'still working {i}\n' },
        ...finishSteps(fx.id),
        { op: 'line', obj: resultLine({ session_id: 'sess-stderr-only' }) },
      ],
    });
    assert.equal(r.errorFile, null, 'a session that is still talking is not killed');
    assert.deepEqual(r.eventsOf('ERROR'), [], 'and no inactivity_timeout is filed against it');
    assert.equal(r.eventsOf('DONE').length, 1, 'it runs to its end');
  } finally { dropFixture(fx); }
});
